spring:
  config: {import: optional:classpath:./secret/db.yml }
  application:
    name: demo3
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 10MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # spring.datasource.url=jdbc:log4jdbc:mariadb://np.levelupseon.com:3306/sample
  # spring.datasource.username=sample
  # spring.datasource.password=1234
  # spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 20000

mybatis:
  type-aliases-package: com.levelupseon.demo3.domain
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
